import Foundation
import Shared
import Database
import Storage
import Capture
import Processing
import Search
import Migration
import SQLCipher

/// Dependency injection container for all app services
/// Owner: APP integration
public actor ServiceContainer {
    private static let rewindCutoffDateDefaultsKey = "rewindCutoffDate"
    private static let rewindSQLCipherPassword = "soiZ58XZJhdka55hLUp18yOtTUTDXz7Diu7Z4JzuwhRwGG13N6Z9RTVU1fGiKkuF"
    private static let rewindCipherCompatibility = 4

    // MARK: - Services

    public let database: DatabaseManager
    public let ftsEngine: FTSManager
    public let storage: StorageManager
    public let capture: CaptureManager
    // ⚠️ RELEASE 2 ONLY - Audio not implemented in Release 1
    // public let audioCapture: AudioCaptureManager
    public let processing: ProcessingManager
    // ⚠️ RELEASE 2 ONLY - Audio not implemented in Release 1
    // public let audioProcessing: AudioProcessingManager
    public let search: SearchManager
    public let migration: MigrationManager
    public let modelManager: ModelManager
    nonisolated public let onboardingManager: OnboardingManager
    public let retentionManager: RetentionManager
    public var dataAdapter: DataAdapter?
    public var processingQueue: FrameProcessingQueue?

    // MARK: - Configuration

    private let databasePath: String
    private let storageConfig: StorageConfig
    private let captureConfig: CaptureConfig
    // ⚠️ RELEASE 2 ONLY
    // private let audioCaptureConfig: AudioCaptureConfig
    private let processingConfig: ProcessingConfig
    // ⚠️ RELEASE 2 ONLY
    // private let audioProcessingConfig: AudioProcessingConfig
    private let searchConfig: SearchConfig

    private var isInitialized = false
    private var ownedRewindConnection: DatabaseConnection?

    // MARK: - Initialization

    public init(
        databasePath: String = AppPaths.databasePath,
        storageConfig: StorageConfig = .default,
        storageCrashReportDirectory: String = EmergencyDiagnostics.crashReportDirectory,
        captureConfig: CaptureConfig = .default,
        // ⚠️ RELEASE 2 ONLY
        // audioCaptureConfig: AudioCaptureConfig = .default,
        processingConfig: ProcessingConfig = .default,
        // ⚠️ RELEASE 2 ONLY
        // audioProcessingConfig: AudioProcessingConfig = .default,
        searchConfig: SearchConfig = .default
    ) {
        self.databasePath = databasePath
        self.storageConfig = storageConfig
        self.captureConfig = captureConfig
        // ⚠️ RELEASE 2 ONLY
        // self.audioCaptureConfig = audioCaptureConfig
        self.processingConfig = processingConfig
        // ⚠️ RELEASE 2 ONLY
        // self.audioProcessingConfig = audioProcessingConfig
        self.searchConfig = searchConfig

        // Initialize all managers
        self.database = DatabaseManager(
            databasePath: databasePath,
            storageRootPath: storageConfig.expandedStorageRootPath
        )
        self.ftsEngine = FTSManager(databasePath: databasePath)
        let storageRootURL = URL(fileURLWithPath: storageConfig.expandedStorageRootPath, isDirectory: true)
        self.storage = StorageManager(
            storageRoot: storageRootURL,
            crashReportDirectory: storageCrashReportDirectory
        )
        self.capture = CaptureManager(config: captureConfig)
        // ⚠️ RELEASE 2 ONLY - Audio initialization commented out
        // self.audioCapture = AudioCaptureManager(config: audioCaptureConfig)
        self.processing = ProcessingManager(config: processingConfig)

        // ⚠️ RELEASE 2 ONLY - Audio processing initialization commented out
        // // Audio processing initialized later after database is ready
        // // Load model path from config file (generated by setup_whisper.sh) or use default
        // let modelPath = WhisperConfigLoader.getModelPath()
        // if WhisperConfigLoader.loadConfig() != nil {
        //     Log.info("Using whisper.cpp config from: \(WhisperConfigLoader.defaultConfigPath)", category: .app)
        //     Log.info("Model: \(modelPath)", category: .app)
        //     if WhisperConfigLoader.isCoreMLEnabled() {
        //         Log.info("CoreML acceleration: enabled", category: .app)
        //     }
        // } else {
        //     Log.warning("whisper_config.json not found, using default model path", category: .app)
        //     Log.info("Model: \(modelPath)", category: .app)
        // }
        //
        // let transcriptionService = WhisperCppTranscriptionService(
        //     modelPath: modelPath,
        //     coreMLModelPath: WhisperConfigLoader.getCoreMLModelPath()
        // )
        //
        // // Audio storage writer
        // let storageRoot = URL(fileURLWithPath: storageConfig.expandedStorageRootPath, isDirectory: true)
        // let audioWriter = AudioSegmentWriter(storageRoot: storageRoot)
        //
        // self.audioProcessing = AudioProcessingManager(
        //     transcriptionService: transcriptionService,
        //     transcriptionQueries: nil,  // Set during initialization
        //     audioWriter: audioWriter,
        //     config: audioProcessingConfig
        // )

        // FTS-only search manager
        self.search = SearchManager(
            database: database,
            ftsEngine: ftsEngine
        )

        // Migration depends on database and processing
        self.migration = MigrationManager(
            database: database,
            processing: processing
        )

        // Model and onboarding managers
        self.modelManager = ModelManager()
        self.onboardingManager = OnboardingManager()

        // Retention manager for data cleanup
        self.retentionManager = RetentionManager(
            database: database,
            storage: storage,
            search: search
        )

        Log.info("ServiceContainer created", category: .app)
    }

    /// Convenience initializer for in-memory/testing
    public init(inMemory: Bool) {
        // Use shared in-memory database so DatabaseManager and FTSManager use the same DB
        let sharedMemoryPath = "file:memdb_test_\(UUID().uuidString)?mode=memory&cache=shared"
        self.databasePath = sharedMemoryPath
        self.storageConfig = .default
        self.captureConfig = .default
        // ⚠️ RELEASE 2 ONLY
        // self.audioCaptureConfig = .default
        self.processingConfig = .default
        // ⚠️ RELEASE 2 ONLY
        // self.audioProcessingConfig = .default
        self.searchConfig = .default

        self.database = DatabaseManager(
            databasePath: sharedMemoryPath,
            storageRootPath: StorageConfig.default.expandedStorageRootPath
        )
        self.ftsEngine = FTSManager(databasePath: sharedMemoryPath)
        let storageRootURL = URL(
            fileURLWithPath: StorageConfig.default.expandedStorageRootPath,
            isDirectory: true
        )
        self.storage = StorageManager(storageRoot: storageRootURL)
        self.capture = CaptureManager()
        // ⚠️ RELEASE 2 ONLY
        // self.audioCapture = AudioCaptureManager()
        self.processing = ProcessingManager()

        // ⚠️ RELEASE 2 ONLY - Audio processing initialization commented out
        // // Audio processing initialized later after database is ready
        // // Use mock transcription service in test mode to avoid loading heavy Whisper model
        // let transcriptionService: any TranscriptionProtocol
        // if inMemory {
        //     transcriptionService = MockTranscriptionService()
        // } else {
        //     // Load model path from config file (generated by setup_whisper.sh) or use default
        //     let modelPath = WhisperConfigLoader.getModelPath()
        //     transcriptionService = WhisperCppTranscriptionService(
        //         modelPath: modelPath,
        //         coreMLModelPath: WhisperConfigLoader.getCoreMLModelPath()
        //     )
        // }
        // let storageRoot = URL(fileURLWithPath: "/tmp/retrace_test", isDirectory: true)
        // let audioWriter = AudioSegmentWriter(storageRoot: storageRoot)
        // self.audioProcessing = AudioProcessingManager(
        //     transcriptionService: transcriptionService,
        //     transcriptionQueries: nil,  // Set during initialization
        //     audioWriter: audioWriter,
        //     config: .default
        // )

        // FTS-only search manager
        self.search = SearchManager(
            database: database,
            ftsEngine: ftsEngine
        )

        self.migration = MigrationManager(
            database: database,
            processing: processing
        )

        // Model and onboarding managers
        self.modelManager = ModelManager()
        self.onboardingManager = OnboardingManager()

        // Retention manager for data cleanup
        self.retentionManager = RetentionManager(
            database: database,
            storage: storage,
            search: search
        )

        Log.info("ServiceContainer created (in-memory mode)", category: .app)
    }

    // MARK: - Lifecycle

    /// Initialize all services in the correct order
    public func initialize() async throws {
        guard !isInitialized else {
            Log.warning("ServiceContainer already initialized", category: .app)
            return
        }

        Log.info("Initializing all services...", category: .app)

        // 1. Initialize database first (creates schema)
        try await database.initialize()
        Log.info("✓ Database initialized", category: .app)

        // 2. Initialize FTS engine (shares same database)
        try await ftsEngine.initialize()
        Log.info("✓ FTS engine initialized", category: .app)

        // 3. Initialize storage (creates directories, loads encryption key)
        try await storage.initialize(config: storageConfig)
        if let walIssue = await storage.currentWALAvailabilityIssue() {
            Log.error(
                "⚠️ Storage initialized in degraded mode - startup WAL initialization failed at \(walIssue.walRootPath): \(walIssue.reason)",
                category: .app
            )
        } else {
            Log.info("✓ Storage initialized", category: .app)
        }

        // DIAGNOSTIC: Log critical paths for troubleshooting database/storage mismatches
        Log.info("=== Storage Configuration ===", category: .app)
        Log.info("Storage Root: \(storageConfig.storageRootPath)", category: .app)
        Log.info("Expanded Root: \(storageConfig.expandedStorageRootPath)", category: .app)
        Log.info("Database Path: \(databasePath)", category: .app)
        let fm = FileManager.default
        let chunksPath = "\(storageConfig.expandedStorageRootPath)/chunks"
        let dbPath = databasePath.hasPrefix("file:")
            ? nil
            : NSString(string: databasePath).expandingTildeInPath
        if let dbPath {
            Log.info("Database exists: \(fm.fileExists(atPath: dbPath))", category: .app)
        } else {
            Log.info("Database exists: n/a (URI database path)", category: .app)
        }
        Log.info("Chunks folder exists: \(fm.fileExists(atPath: chunksPath))", category: .app)

        // SAFETY: If database exists but chunks folder is missing, clear processing queue
        // This prevents infinite retry loops from orphaned frame records
        if let dbPath, fm.fileExists(atPath: dbPath), !fm.fileExists(atPath: chunksPath) {
            Log.error("⚠️ CRITICAL: Database exists but chunks folder missing!", category: .app)
            Log.warning("Clearing processing queue to prevent failures...", category: .app)

            // Clear processing queue - frames can't be processed without video files
            // Note: WAL is relative to storageRoot so it's already at the correct location
            try await database.clearProcessingQueue()

            Log.info("✓ Cleared processing queue (frames have no video files)", category: .app)
        }
        Log.info("============================", category: .app)

        // 4. Initialize processing (sets config)
        try await processing.initialize(config: processingConfig)
        Log.info("✓ Processing initialized", category: .app)

        // ⚠️ RELEASE 2 ONLY - Audio processing initialization commented out
        // // 5. Initialize audio processing (loads whisper.cpp model and connects to database)
        // guard let dbPointer = await database.getConnection() else {
        //     throw ServiceError.databaseNotReady
        // }
        // let audioTranscriptionQueries = AudioTranscriptionQueries(db: dbPointer)
        // let storageRoot = await storage.getStorageDirectory()
        // let audioWriter = AudioSegmentWriter(storageRoot: storageRoot)
        // try await audioProcessing.initialize(
        //     transcriptionQueries: audioTranscriptionQueries,
        //     audioWriter: audioWriter
        // )
        // Log.info("✓ Audio processing initialized", category: .app)

        // 6. Initialize search manager
        try await search.initialize(config: searchConfig)
        Log.info("✓ Search initialized", category: .app)

        // 7. Initialize processing queue (workers started after full initialization)
        let queue = FrameProcessingQueue(
            database: database,
            storage: storage,
            processing: processing,
            search: search,
            config: .default
        )
        self.processingQueue = queue
        Log.info("✓ Processing queue initialized", category: .app)

        // 8. Migration doesn't need explicit initialization
        Log.info("✓ Migration ready", category: .app)

        // 9. Initialize DataAdapter with connections directly
        guard let dbPointer = await database.getConnection() else {
            throw ServiceError.databaseNotReady
        }

        // Create connections and config for Retrace
        let retraceConnection = SQLiteConnection(db: dbPointer)
        let retraceConfig = DatabaseConfig.retrace(storageRoot: storageConfig.expandedStorageRootPath)
        let retraceImageExtractor = HEVCStorageExtractor(storageManager: storage)

        let adapter = DataAdapter(
            retraceConnection: retraceConnection,
            retraceReadConnectionPool: database.readConnectionPool,
            retraceConfig: retraceConfig,
            retraceImageExtractor: retraceImageExtractor,
            database: database
        )

        // Register Rewind source if user opted in
        let defaults = UserDefaults(suiteName: "io.retrace.app") ?? .standard
        let useRewindData = defaults.bool(forKey: "useRewindData")
        Log.info("Checking Rewind source during initialization: useRewindData=\(useRewindData)", category: .app)

        if useRewindData {
            await configureRewindSource(adapter: adapter)
        } else {
            Log.info("⊘ Rewind source not registered during initialization (useRewindData is false)", category: .app)
        }

        // Initialize the adapter
        try await adapter.initialize()
        self.dataAdapter = adapter
        Log.info("✓ DataAdapter initialized", category: .app)

        // 10. Start retention manager (runs periodic cleanup based on user settings)
        await retentionManager.start()
        Log.info("✓ Retention manager started", category: .app)

        // Capture is initialized when startCapture() is called

        isInitialized = true
        Log.info("All services initialized successfully", category: .app)

        // Start processing queue workers immediately after initialization
        // Safe to run anytime since all DB operations go through DatabaseManager actor
        await queue.startWorkers()
        Log.info("✓ Processing queue workers started (\(ProcessingQueueConfig.default.workerCount) workers)", category: .app)
    }

    /// Register Rewind data source if user has opted in
    /// Can be called after initialization (e.g., after onboarding completes)
    public func registerRewindSourceIfEnabled() async throws {
        guard isInitialized else {
            Log.warning("Cannot register Rewind source - ServiceContainer not initialized", category: .app)
            return
        }

        guard let adapter = dataAdapter else {
            Log.warning("Cannot register Rewind source - DataAdapter not available", category: .app)
            return
        }

        let defaults = UserDefaults(suiteName: "io.retrace.app") ?? .standard
        let useRewindData = defaults.bool(forKey: "useRewindData")
        Log.info("Checking if Rewind source should be registered: useRewindData=\(useRewindData)", category: .app)

        if useRewindData {
            // Check if already registered
            let sources = await adapter.registeredSources
            if sources.contains(.rewind) {
                Log.info("Rewind source already registered, skipping", category: .app)
                return
            }

            await configureRewindSource(adapter: adapter)
            Log.info("✓ Rewind source registered and connected after initialization", category: .app)
        } else {
            Log.info("⊘ Rewind source not registered (useRewindData is false)", category: .app)
        }
    }

    /// Set Rewind data source enabled/disabled and update connection accordingly
    /// - Parameter enabled: Whether to connect or disconnect Rewind data
    public func setRewindSourceEnabled(_ enabled: Bool) async {
        guard isInitialized else {
            Log.warning("Cannot change Rewind source - ServiceContainer not initialized", category: .app)
            return
        }

        guard let adapter = dataAdapter else {
            Log.warning("Cannot change Rewind source - DataAdapter not available", category: .app)
            return
        }

        // Save preference
        let defaults = UserDefaults(suiteName: "io.retrace.app") ?? .standard
        defaults.set(enabled, forKey: "useRewindData")

        if enabled {
            // Connect Rewind source if not already connected
            let sources = await adapter.registeredSources
            if sources.contains(.rewind) {
                Log.info("Rewind source already connected", category: .app)
                return
            }
            await configureRewindSource(adapter: adapter)
            Log.info("✓ Rewind source connected", category: .app)
        } else {
            // Disconnect Rewind source
            await adapter.disconnectRewind()
            closeOwnedRewindConnection()
            Log.info("✓ Rewind source disconnected", category: .app)
        }
    }

    @discardableResult
    public func refreshRewindCutoffDate() async -> Bool {
        guard isInitialized else {
            Log.warning("Cannot refresh Rewind cutoff - ServiceContainer not initialized", category: .app)
            return false
        }

        guard let adapter = dataAdapter else {
            Log.warning("Cannot refresh Rewind cutoff - DataAdapter not available", category: .app)
            return false
        }

        let defaults = UserDefaults(suiteName: "io.retrace.app") ?? .standard
        guard defaults.bool(forKey: "useRewindData") else {
            Log.info("Rewind cutoff updated in settings while Rewind data is disabled", category: .app)
            return false
        }

        let cutoffDate = Self.rewindCutoffDate(in: defaults)
        if await adapter.updateRewindCutoffDate(cutoffDate) {
            Log.info("✓ Active Rewind cutoff refreshed to \(cutoffDate)", category: .app)
            return true
        }

        await configureRewindSource(adapter: adapter)
        let sources = await adapter.registeredSources
        let refreshed = sources.contains(.rewind)
        if refreshed {
            Log.info("✓ Rewind source configured with refreshed cutoff \(cutoffDate)", category: .app)
        } else {
            Log.warning("Failed to refresh Rewind cutoff because Rewind source could not be configured", category: .app)
        }
        return refreshed
    }

    public func latestRewindFrameDate() async -> Date? {
        Self.latestRewindFrameDate(databasePath: AppPaths.rewindDBPath)
    }

    /// Helper to configure Rewind source on DataAdapter
    private func configureRewindSource(adapter: DataAdapter) async {
        let rewindDBPath = NSString(string: AppPaths.rewindDBPath).expandingTildeInPath

        guard FileManager.default.fileExists(atPath: rewindDBPath) else {
            Log.warning("Rewind database not found at: \(rewindDBPath)", category: .app)
            return
        }

        let rewindConnection: DatabaseConnection
        do {
            rewindConnection = try Self.makeRewindConnection(databasePath: rewindDBPath)
        } catch {
            Log.error("[ServiceContainer] Failed to open Rewind database: \(error)", category: .app)
            return
        }

        let defaults = UserDefaults(suiteName: "io.retrace.app") ?? .standard
        let cutoffDate = Self.rewindCutoffDate(in: defaults)
        if Self.storedRewindCutoffDate(in: defaults) != nil {
            Log.info("[ServiceContainer] Using user-configured Rewind cutoff \(cutoffDate)", category: .app)
        } else {
            Log.info("[ServiceContainer] Using default Rewind cutoff \(cutoffDate)", category: .app)
        }

        // Create connection and config
        ownedRewindConnection = rewindConnection
        let rewindSearchConnectionPool = SQLiteReadConnectionPool(
            label: "rewind_search",
            connectionFactory: { [rewindDBPath] in
                try Self.makeRewindConnection(databasePath: rewindDBPath)
            }
        )
        let rewindConfig = DatabaseConfig.rewind(cutoffDate: cutoffDate)
        // Chunks directory is always in the same parent directory as the database
        let rewindDBDir = (rewindDBPath as NSString).deletingLastPathComponent
        let rewindChunksPath = "\(rewindDBDir)/chunks"
        let rewindImageExtractor = AVAssetExtractor(storageRoot: rewindChunksPath)

        await adapter.configureRewind(
            connection: rewindConnection,
            config: rewindConfig,
            imageExtractor: rewindImageExtractor,
            cutoffDate: cutoffDate,
            searchConnectionPool: rewindSearchConnectionPool
        )
        Log.info("✓ Rewind source configured during initialization", category: .app)
    }

    private func closeOwnedRewindConnection() {
        guard let db = ownedRewindConnection?.getConnection() else {
            ownedRewindConnection = nil
            return
        }

        let rc = sqlite3_close_v2(db)
        if rc != SQLITE_OK {
            let message = String(cString: sqlite3_errmsg(db))
            Log.warning(
                "[ServiceContainer] Failed to close Rewind database connection (\(rc)): \(message)",
                category: .app
            )
        }

        ownedRewindConnection = nil
    }

    private nonisolated static func makeRewindConnection(databasePath: String) throws -> DatabaseConnection {
        try SQLiteReadOnlyConnectionFactory.makeRewindConnection(
            databasePath: databasePath,
            password: rewindSQLCipherPassword,
            cipherCompatibility: rewindCipherCompatibility
        )
    }

    nonisolated static func latestRewindFrameDate(databasePath: String) -> Date? {
        let expandedPath = NSString(string: databasePath).expandingTildeInPath

        guard FileManager.default.fileExists(atPath: expandedPath) else {
            Log.info("[ServiceContainer] Rewind database not found while probing latest frame: \(expandedPath)", category: .app)
            return nil
        }

        let connection: DatabaseConnection
        do {
            connection = try makeRewindConnection(databasePath: expandedPath)
        } catch {
            Log.error("[ServiceContainer] Failed to open Rewind database while probing latest frame", category: .app, error: error)
            return nil
        }

        guard let db = connection.getConnection() else {
            Log.warning("[ServiceContainer] Rewind database connection was nil while probing latest frame", category: .app)
            return nil
        }

        var statement: OpaquePointer?
        defer {
            sqlite3_finalize(statement)
            let closeResult = sqlite3_close_v2(db)
            if closeResult != SQLITE_OK {
                let message = String(cString: sqlite3_errmsg(db))
                Log.warning(
                    "[ServiceContainer] Failed to close Rewind probe connection (\(closeResult)): \(message)",
                    category: .app
                )
            }
        }

        let sql = "SELECT MAX(createdAt) FROM frame;"
        guard sqlite3_prepare_v2(db, sql, -1, &statement, nil) == SQLITE_OK else {
            let message = String(cString: sqlite3_errmsg(db))
            Log.warning("[ServiceContainer] Failed to prepare latest Rewind frame probe: \(message)", category: .app)
            return nil
        }

        guard sqlite3_step(statement) == SQLITE_ROW else {
            let message = String(cString: sqlite3_errmsg(db))
            Log.warning("[ServiceContainer] Latest Rewind frame probe did not return a row: \(message)", category: .app)
            return nil
        }

        guard let value = sqlite3_column_text(statement, 0) else {
            Log.info("[ServiceContainer] Latest Rewind frame probe returned no timestamp", category: .app)
            return nil
        }

        let latestFrameTimestamp = String(cString: value)
        guard let date = DatabaseConfig.rewindDateFormatter.date(from: latestFrameTimestamp) else {
            Log.warning(
                "[ServiceContainer] Failed to parse latest Rewind frame timestamp: \(latestFrameTimestamp)",
                category: .app
            )
            return nil
        }

        return date
    }

    public nonisolated static func defaultRewindCutoffDate(calendar: Calendar = .current) -> Date {
        var components = DateComponents()
        components.year = 2025
        components.month = 12
        components.day = 20
        components.hour = 0
        components.minute = 0
        components.second = 0

        return calendar.date(from: components) ?? Date(timeIntervalSince1970: 1_766_188_800)
    }

    public nonisolated static func storedRewindCutoffDate(in defaults: UserDefaults) -> Date? {
        if let storedDate = defaults.object(forKey: rewindCutoffDateDefaultsKey) as? Date {
            return storedDate
        }

        if let storedNumber = defaults.object(forKey: rewindCutoffDateDefaultsKey) as? NSNumber {
            return Date(timeIntervalSince1970: storedNumber.doubleValue)
        }

        return nil
    }

    public nonisolated static func rewindCutoffDate(
        in defaults: UserDefaults,
        calendar: Calendar = .current
    ) -> Date {
        storedRewindCutoffDate(in: defaults) ?? defaultRewindCutoffDate(calendar: calendar)
    }

    /// Shutdown all services gracefully
    public func shutdown() async throws {
        guard isInitialized else { return }

        Log.info("Shutting down all services...", category: .app)

        // Stop capture if running
        if await capture.isCapturing {
            try await capture.stopCapture()
            Log.info("✓ Capture stopped", category: .app)
        }

        // ⚠️ RELEASE 2 ONLY - Audio capture stop commented out
        // // Stop audio capture if running
        // if await audioCapture.isCapturing {
        //     try await audioCapture.stopCapture()
        //     Log.info("✓ Audio capture stopped", category: .app)
        // }

        // Stop processing queue workers
        await processingQueue?.stopWorkers()
        Log.info("✓ Processing queue workers stopped", category: .app)

        // ⚠️ RELEASE 2 ONLY
        // // Audio processing will complete when stream ends
        // Log.info("✓ Audio processing drained", category: .app)

        // Stop retention manager
        await retentionManager.stop()
        Log.info("✓ Retention manager stopped", category: .app)

        // Shutdown DataAdapter (disconnects all sources)
        await dataAdapter?.shutdown()
        closeOwnedRewindConnection()
        Log.info("✓ DataAdapter shutdown", category: .app)

        try await ftsEngine.close()
        Log.info("✓ FTS engine closed", category: .app)

        try await database.close()
        Log.info("✓ Database closed", category: .app)

        isInitialized = false
        Log.info("All services shutdown successfully", category: .app)
    }

    // MARK: - Service Access

    /// Check if services are initialized
    public var initialized: Bool {
        isInitialized
    }

    /// Get database statistics
    public func getDatabaseStats() async throws -> DatabaseStatistics {
        try await database.getStatistics()
    }

    /// Get app session count (distinct from video segment count)
    public func getAppSessionCount() async throws -> Int {
        try await database.getAppSessionCount()
    }

    /// Get quick database statistics (single query, for feedback diagnostics)
    public func getDatabaseStatsQuick() async throws -> (frameCount: Int, sessionCount: Int) {
        try await database.getStatisticsQuick()
    }

    /// Get search statistics
    public func getSearchStats() async -> SearchStatistics {
        await search.getStatistics()
    }

    /// Get capture statistics
    public func getCaptureStats() async -> CaptureStatistics {
        await capture.getStatistics()
    }

    /// Get processing statistics
    public func getProcessingStats() async -> ProcessingStatistics {
        await processing.getStatistics()
    }
}

// MARK: - Default Configurations

extension StorageConfig {
    public static var `default`: StorageConfig {
        // Read settings from UserDefaults (synced with Settings UI)
        // Defaults: retention = forever (0/nil), storage = unlimited (500GB max)
        let defaults = UserDefaults(suiteName: "io.retrace.app") ?? .standard
        let retentionDays = defaults.object(forKey: "retentionDays") as? Int ?? 0
        let maxStorageGB = defaults.object(forKey: "maxStorageGB") as? Double ?? 500.0

        return StorageConfig(
            storageRootPath: AppPaths.storageRoot,
            retentionDays: retentionDays == 0 ? nil : retentionDays, // 0 = forever
            maxStorageGB: maxStorageGB,
            segmentDurationSeconds: 300  // 5 minutes
        )
    }
}

extension CaptureConfig {
    public static var `default`: CaptureConfig {
        // Read settings from UserDefaults (synced with Settings UI)
        let defaults = UserDefaults(suiteName: "io.retrace.app") ?? .standard
        let captureIntervalSeconds = defaults.object(forKey: "captureIntervalSeconds") as? Double ?? 2.0
        // Private/incognito redaction toggle (AXTitle marker-based)
        let excludePrivateWindows = defaults.object(forKey: "excludePrivateWindows") as? Bool ?? false
        // excludeCursor = true means hide cursor, so showCursor = !excludeCursor
        let excludeCursor = defaults.object(forKey: "excludeCursor") as? Bool ?? false
        let showCursor = !excludeCursor
        // Delete duplicate frames setting controls adaptive capture (deduplication)
        // Default to true - deduplication enabled by default
        let deleteDuplicateFrames = defaults.object(forKey: "deleteDuplicateFrames") as? Bool ?? true
        // Deduplication threshold - how similar frames must be to be considered duplicates
        let deduplicationThreshold = defaults.object(forKey: "deduplicationThreshold") as? Double ?? CaptureConfig.defaultDeduplicationThreshold
        let keepFramesOnMouseMovement = defaults.object(forKey: "keepFramesOnMouseMovement") as? Bool ?? true
        let enableCustomPatternWindowRedaction = defaults.object(forKey: "enableCustomPatternWindowRedaction") as? Bool ?? true

        // Parse excluded apps from settings (stored as JSON array of ExcludedAppInfo)
        var excludedBundleIDs: Set<String> = ["com.apple.loginwindow"] // Always exclude login screen
        if let excludedAppsString = defaults.string(forKey: "excludedApps"),
           !excludedAppsString.isEmpty,
           let data = excludedAppsString.data(using: .utf8) {
            // Decode the JSON array and extract bundle IDs
            struct ExcludedAppInfo: Codable {
                let bundleID: String
            }
            if let apps = try? JSONDecoder().decode([ExcludedAppInfo].self, from: data) {
                for app in apps {
                    excludedBundleIDs.insert(app.bundleID)
                }
            }
        }

        let redactWindowTitlePatterns = enableCustomPatternWindowRedaction
            ? parseRedactionPatterns(defaults.string(forKey: "redactWindowTitlePatterns"))
            : []
        let redactBrowserURLPatterns = enableCustomPatternWindowRedaction
            ? parseRedactionPatterns(defaults.string(forKey: "redactBrowserURLPatterns"))
            : []

        // Capture on window change - instantly capture when switching apps/windows
        let captureOnWindowChange = defaults.object(forKey: "captureOnWindowChange") as? Bool ?? true
        let captureOnMouseClick = defaults.object(forKey: "captureOnMouseClick") as? Bool ?? false

        return CaptureConfig(
            captureIntervalSeconds: captureIntervalSeconds,
            adaptiveCaptureEnabled: deleteDuplicateFrames, // Controlled by "Delete duplicate frames" setting
            deduplicationThreshold: deduplicationThreshold, // Controlled by "Similarity threshold" slider in settings
            keepFramesOnMouseMovement: keepFramesOnMouseMovement,
            maxResolution: .uhd4K,
            excludedAppBundleIDs: excludedBundleIDs,
            excludePrivateWindows: excludePrivateWindows,
            showCursor: showCursor,
            redactWindowTitlePatterns: redactWindowTitlePatterns,
            redactBrowserURLPatterns: redactBrowserURLPatterns,
            captureOnWindowChange: captureOnWindowChange,
            captureOnMouseClick: captureOnMouseClick
        )
    }

    private static func parseRedactionPatterns(_ raw: String?) -> [String] {
        guard let raw, !raw.isEmpty else { return [] }
        return raw
            .split(whereSeparator: { $0 == "," || $0 == "\n" })
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }
}

extension ProcessingConfig {
    /// Escape hatch for re-enabling Vision's language-correction pass without a rebuild:
    /// `defaults write io.retrace.app retrace.ocr.languageCorrectionEnabled -bool YES`
    ///
    /// Unset reads as false, which is the measured-better default (see `ProcessingConfig`).
    static var ocrLanguageCorrectionOverride: Bool {
        let defaults = UserDefaults(suiteName: MasterKeyManager.settingsSuiteName) ?? .standard
        return defaults.bool(forKey: "retrace.ocr.languageCorrectionEnabled")
    }

    public static var `default`: ProcessingConfig {
        ProcessingConfig(
            accessibilityEnabled: false,  // Disabled - reads live screen, not video frames
            ocrAccuracyLevel: .accurate,
            recognitionLanguages: ["en-US"],
            minimumConfidence: 0.5,
            ocrLanguageCorrectionEnabled: ocrLanguageCorrectionOverride
        )
    }
}

extension SearchConfig {
    public static var `default`: SearchConfig {
        SearchConfig(
            semanticSearchEnabled: false,  // Semantic search disabled
            defaultResultLimit: 50,
            minimumRelevanceScore: 0.1
        )
    }
}

// ⚠️ RELEASE 2 ONLY - Audio config extensions commented out
// extension AudioCaptureConfig {
//     public static var `default`: AudioCaptureConfig {
//         AudioCaptureConfig(
//             microphoneEnabled: true,
//             systemAudioEnabled: true,
//             voiceProcessingEnabled: true,
//             hasConsentedToMeetingRecording: false,
//             bufferDurationSeconds: 30.0,
//             targetSampleRate: 16000,
//             targetChannels: 1,
//             meetingAppBundleIDs: AudioCaptureConfig.defaultMeetingApps
//         )
//     }
// }
//
// extension AudioProcessingConfig {
//     public static var `default`: AudioProcessingConfig {
//         AudioProcessingConfig(
//             enableWordLevelTimestamps: true,
//             minimumConfidence: 0.5,
//             maxBufferDuration: 30.0,
//             transcriptionCallback: nil
//         )
//     }
// }

// MARK: - Errors

enum ServiceError: Error {
    case databaseNotReady
    case initializationFailed(String)
}
